#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
    brew bundle check >/dev/null 2>&1 || {
        echo "==> Installing Homebrew dependencies..."
        brew bundle
    }
fi

if [ -f ".tool-versions" ]; then
    echo "==> Installing tools (with asdf)..."
    asdf install
fi

if [ -f "package.json" ]; then
    echo "==> Installing npm dependencies (with yarn)..."
    yarn install
fi
