#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

export NODE_ENV="test"

test -d "$HOME/.asdf/shims" && {
    export PATH="$HOME/.asdf/shims":"$PATH"
}

echo "Running tests..."
date "+%H:%M:%S"

script/test

echo "Tests ended..."
date "+%H:%M:%S"
